name: checks
on:
  pull_request:
    branches: 
      - main
  push:
    branches: 
      - main
jobs:
  build-project:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.3.4
      - uses: actions/setup-node@@v2.1.2

      - name: install
        run: npm i

      - name: lint
        run: npm run lint

      - name: test
        run: npm run test

      - name: build
        run: npm run build
      
      - name: publish
        run: npm publish --access=public
        if: github.event == 'push'
